[package]
name = "kenobi-chess-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
scanner-rust = "2.0.17"
criterion = "0.5.1"
num-derive = "0.4.2"
num-traits = "0.2.19"
regex = "1.10.6"

[profile.dev]
opt-level = 3
lto = "fat"

[profile.release]
opt-level = 3
lto = "fat"

[profile.bench]
opt-level = 3
lto = "fat"

[profile.test]
opt-level = 1
lto = false