//! Zobrist hashing is a way to hash the board position
//! It quickens up the access and compresses the position
//! Used by e.g. transposition table

use crate::board::Board;
use crate::move_generator::NO_PASSANT;
use crate::piece::Colour;
use crate::piece::Colour::BLACK;

// const PIECES_POSITIONS: usize = 64*12;
const ZOBRIST_CONSTANTS: usize = 64*12 + 8 + 16 + 1;
const ZOBRIST_SEED: u64 = 0xFFAA_B58C_5833_FE89u64;

/// Each significant board position atomic setting gets its own pseudo-random key
/// (i.e. white rook on square A1, en passant on file C, castling rights Kkq, black to play)
/// Hash is generated by XORing all the relevant keys
pub struct ZobristTable {
    pub pieces: [[u64; 64]; 12],
    pub en_passant: [u64; 8], // we only need to know the file of en passant
    pub castling_rights: [u64; 16], // 2^4 = 16 combinations, little-endian
    pub active_player: u64 // we only need to indicate if black is the active player
}

pub const ZOBRIST_TABLE: ZobristTable = {
    let mut seed = ZOBRIST_SEED;
    let mut table = [0u64; ZOBRIST_CONSTANTS];

    let mut i = 0;

    while i < ZOBRIST_CONSTANTS {
        table[i] = xorshift(seed);
        seed = table[i];
        i += 1;
    }

    unsafe { std::mem::transmute(table) }
};

/// Applies xorshift for the given seed and outputs a pseudo-random number.
/// PRNG
const fn xorshift(mut seed: u64) -> u64 {
    seed ^= seed << 13;
    seed ^= seed >> 7;
    seed ^= seed << 17;

    seed
}

/// Hashes a given board position, using Zobrist hashing
pub fn zobrist_hash(board: &Board) -> u64 {
    let mut hash = 0u64;

    for i in 0..board.piece_bitboards.len() {
        hash ^= zobrist_piece(board.piece_bitboards[i], i);
    }

    hash ^= zobrist_en_passant(board.en_passant_possibility);
    hash ^= zobrist_castling_rights(board.castling_rights);
    hash ^= zobrist_active_player(&board.active_player);

    hash
}

/// Hashes a given piece type using Zobrist hashing, given a piece bitboard and its type index, as specified by Piece enum
fn zobrist_piece(piece_bitboard: u64, piece_index: usize) -> u64 {
    let mut hash = 0u64;
    let mut bitboard = piece_bitboard;

    while bitboard > 0 {
        let tile = bitboard & bitboard.wrapping_neg();
        bitboard -= tile;

        let square = tile.checked_ilog2().unwrap_or_default() as usize;

        hash ^= ZOBRIST_TABLE.pieces[piece_index][square];
    }

    hash
}

/// Hashes a given en passant possibility using Zobrist hashing, given a current en passant square or
/// NO_PASSANT for no en passant possibility.
fn zobrist_en_passant(en_passant_square: u8) -> u64 {
    let mut hash = 0u64;

    if en_passant_square == NO_PASSANT { return hash; }

    let file = (en_passant_square % 8) as usize;
    hash ^= ZOBRIST_TABLE.en_passant[file];

    hash
}

/// Hashes given castling rights using Zobrist hashing.
pub fn zobrist_castling_rights(castling_rights: u8) -> u64 {
    ZOBRIST_TABLE.castling_rights[castling_rights as usize]
}

/// Hashes a given active player colour using Zobrist hashing:
/// 0 for WHITE, ZOBRIST_TABLE.active_player for BLACK
fn zobrist_active_player(active_player: &Colour) -> u64 {
    if *active_player == BLACK { return ZOBRIST_TABLE.active_player; }

    0u64
}

#[cfg(test)]
mod tests {
    use std::time::Instant;
    use crate::piece::Colour::WHITE;
    use crate::piece::Piece::{BISHOP, KING, KNIGHT, PAWN, QUEEN, ROOK};
    use super::*;

    #[test]
    fn check_zobrist_table() {
        let mut seed = ZOBRIST_SEED;
        seed ^= seed << 13;
        seed ^= seed >> 7;
        seed ^= seed << 17;

        assert_eq!(seed, ZOBRIST_TABLE.pieces[0][0]);

        seed ^= seed << 13;
        seed ^= seed >> 7;
        seed ^= seed << 17;
        assert_eq!(seed, ZOBRIST_TABLE.pieces[0][1]);

        assert_eq!(64, ZOBRIST_TABLE.pieces[0].len());
        assert_eq!(12, ZOBRIST_TABLE.pieces.len());
    }

    #[test]
    fn check_zobrist_seed() {
        let keys = [Vec::from(ZOBRIST_TABLE.pieces.as_flattened()), Vec::from(&ZOBRIST_TABLE.en_passant), Vec::from(&ZOBRIST_TABLE.castling_rights), Vec::from(&[ZOBRIST_TABLE.active_player])].concat();

        for i in 0..ZOBRIST_CONSTANTS {
            for j in i+1..ZOBRIST_CONSTANTS {
                if keys[i] == keys[j] { panic!() }
            }
        }

        assert!(true);
    }

    #[test]
    fn check_zobrist_piece() {
        assert_eq!(ZOBRIST_TABLE.pieces[1][0], zobrist_piece(0x0000_0000_0000_0001, 1));
        assert_eq!(ZOBRIST_TABLE.pieces[1][0] ^ ZOBRIST_TABLE.pieces[1][47], zobrist_piece(0x0000_8000_0000_0001, 1));
        assert_eq!(ZOBRIST_TABLE.pieces[10][63], zobrist_piece(0x8000_0000_0000_0000, 10));
    }

    #[test]
    fn check_zobrist_en_passant() {
        assert_eq!(ZOBRIST_TABLE.en_passant[3], zobrist_en_passant(16+3));
        assert_eq!(ZOBRIST_TABLE.en_passant[5], zobrist_en_passant(40+5));
        assert_eq!(0, zobrist_en_passant(64));
    }

    #[test]
    fn check_zobrist_castling_rights() {
        assert_eq!(ZOBRIST_TABLE.castling_rights[15], zobrist_castling_rights(15));
        assert_eq!(ZOBRIST_TABLE.castling_rights[14], zobrist_castling_rights(14));
        assert_eq!(ZOBRIST_TABLE.castling_rights[10], zobrist_castling_rights(10));
        assert_eq!(ZOBRIST_TABLE.castling_rights[0], zobrist_castling_rights(0));
        assert_eq!(ZOBRIST_TABLE.castling_rights[1], zobrist_castling_rights(1));
    }

    #[test]
    fn check_zobrist_active_player() {
        assert_eq!(ZOBRIST_TABLE.active_player, zobrist_active_player(&BLACK));
        assert_eq!(0, zobrist_active_player(&WHITE));
    }

    #[test]
    fn check_zobrist_hash() {
        let mut board = Board::new();
        board.read_fen("rn2k3/8/8/8/P7/6PP/8/2BQK2R b q a3 0 1");

        let expected = ZOBRIST_TABLE.pieces[KING as usize][3] ^ ZOBRIST_TABLE.pieces[QUEEN as usize][4]
        ^ ZOBRIST_TABLE.pieces[BISHOP as usize][5] ^ ZOBRIST_TABLE.pieces[ROOK as usize][0]
        ^ ZOBRIST_TABLE.pieces[PAWN as usize][16] ^ ZOBRIST_TABLE.pieces[PAWN as usize][17]
        ^ ZOBRIST_TABLE.pieces[PAWN as usize][31] ^ ZOBRIST_TABLE.pieces[KING as usize + 6 * BLACK as usize][59]
        ^ ZOBRIST_TABLE.pieces[ROOK as usize + 6 * BLACK as usize][63] ^ ZOBRIST_TABLE.pieces[KNIGHT as usize + 6 * BLACK as usize][62]
        ^ ZOBRIST_TABLE.en_passant[7] ^ ZOBRIST_TABLE.castling_rights[1] ^ ZOBRIST_TABLE.active_player;

        let time = Instant::now();
        assert_eq!(expected, zobrist_hash(&board));
        let duration = time.elapsed();
        println!("zobrist_hash lasted for: {:?}", duration);
    }
}
