//! Zobrist hashing is a way to hash the board position
//! It quickens up the access and compresses the position
//! Used by e.g. transposition table

use crate::board::Board;

const PIECES_POSITIONS: usize = 64*12;
const ZOBRIST_CONSTANTS: usize = 64*12 + 8 + 16 + 1;
const ZOBRIST_SEED: u64 = 0xFFAA_B58C_5833_FE89u64;

/// Each significant board position atomic setting gets its own pseudo-random key
/// (i.e. white rook on square A1, en passant on file C, castling rights Kkq, black to play)
/// Hash is generated by XORing all the relevant keys
pub struct ZobristTable {
    pub pieces: [[u64; 64]; 12],
    pub en_passant: [u64; 8], // we only need to know the file of en passant
    pub castling_rights: [u64; 16], // there are 2^4=16 possible combinations of castling rights
    pub active_player: u64 // we only need to indicate if black is the active player
}

pub const ZOBRIST_TABLE: ZobristTable = {
    let mut seed = ZOBRIST_SEED;
    let mut table = [0u64; ZOBRIST_CONSTANTS];

    let mut i = 0;

    while i < ZOBRIST_CONSTANTS {
        table[i] = xorshift(seed);
        seed = table[i];
        i += 1;
    }

    unsafe { std::mem::transmute(table) }
};

/// Applies xorshift for the given seed and outputs a pseudo-random number.
/// PRNG
const fn xorshift(mut seed: u64) -> u64 {
    seed ^= seed << 13;
    seed ^= seed >> 7;
    seed ^= seed << 17;

    seed
}

pub fn zobrist_hash(board: &Board) -> u64 {
    let mut hash = 0u64;

    hash
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn check_zobrist_table() {
        let mut seed = ZOBRIST_SEED;
        seed ^= seed << 13;
        seed ^= seed >> 7;
        seed ^= seed << 17;

        assert_eq!(seed, ZOBRIST_TABLE.pieces[0][0]);

        seed ^= seed << 13;
        seed ^= seed >> 7;
        seed ^= seed << 17;
        assert_eq!(seed, ZOBRIST_TABLE.pieces[0][1]);

        assert_eq!(64, ZOBRIST_TABLE.pieces[0].len());
        assert_eq!(12, ZOBRIST_TABLE.pieces.len());
    }
}
